### ISSUE TITLE
[Wiki] “工具链 安装 Win” 中 GCC-ARM-NONE-EABI 下载链接过时

### ISSUE THREAD

**Issue by sshwy** [Meta-Team/Meta-Embedded#20]
原链接：https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

点进去后会提示该页面已废弃，是否应该修改为 https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

**Comment by liuzikai** [comment]
感谢指出，文档已更新，不过原链接依然保留了，因为新版本还未经测试，如果有不兼容的情况可能需要使用旧版本
